apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: processor-scaler
  namespace: app
  labels:
    app: processor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: processor
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: threads_busy
      target:
        type: AverageValue
        averageValue: "3"